prefix dcterms: <http://purl.org/dc/terms/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
prefix purl: <http://purl.org/library/>

SELECT count(schema:creator) ?name
WHERE
 {
  ?book schema:creator ?author.
  ?author schema:name ?name.
} 